//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoreMan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPayment
    {
        public int AccountPaymentId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SquarePaymentId { get; set; }
        public int AccountTypeId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string IdempotencyKey { get; set; }
        public string Nonce { get; set; }
    
        public virtual User User { get; set; }
    }
}
