//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoreMan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoreListStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChoreListStatu()
        {
            this.ChoreLists = new HashSet<ChoreList>();
        }
    
        public int ChoreListStatusId { get; set; }
        public string ChoreListStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChoreList> ChoreLists { get; set; }
        public virtual ChoreListStatu ChoreListStatus1 { get; set; }
        public virtual ChoreListStatu ChoreListStatu1 { get; set; }
    }
}
