//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoreMan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> ChoreUserId { get; set; }
        public Nullable<int> ChoreId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateScheduled { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public bool IsComplete { get; set; }
        public string ErrorLog { get; set; }
        public bool IsVerified { get; set; }
        public bool IsSent { get; set; }
        public string Sid { get; set; }
    
        public virtual Chore Chore { get; set; }
        public virtual ChoreUser ChoreUser { get; set; }
    }
}
